services:
  finfrases-api:
    image: docker.io/williansilva51/fin-frases
    container_name: finfrases-api
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - API_PREFIX=${API_PREFIX-/api}
      - REDIS_URI=${REDIS_URI}
      - MONGO_URI=${MONGO_URI}
    expose:
      - "8000"
    networks:
      - finfrases-network
      - caddy-network

networks:
  finfrases-network:
    name: finfrases-network
    driver: bridge
  caddy-network:
    external: true
