services:
  finfrases-api:
    image: docker.io/williansilva51/fin-frases
    container_name: finfrases-api
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - API_PREFIX=${API_PREFIX:-/api}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_URI=${REDIS_URI:-redis://:${REDIS_PASSWORD:-defaultpassword}@${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
      - MONGO_URI=${MONGO_URI}
    expose:
      - "8000"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - finfrases-network
      - caddy-network

networks:
  finfrases-network:
    name: finfrases-network
    driver: bridge
  caddy-network:
    external: true
